model: yolov5n-cls.pt
data: fashion-mnist
epochs: 10
batch_size: 64
imgsz: 128
nosave: false
cache: null
device: ''
workers: 8
project: YOLOv5-cls
name: yolov5n-cls.pt-fashion-mnist
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: YOLOv5-cls\yolov5n-cls.pt-fashion-mnist4
